export const arts = {
	bernmuseum: [
		{
			artiste: "Alice Marie Louise Bailly (1872–1938)",
			titre: "Jeune musicien (Hans Jegerlehner)",
			date: "1926",
			dimensions: {
				hauteur: "34",
				longueur: "65",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1926",
			image: "src/images/bernmuseum/fK77.jpg",
			provenance: {
				nom: "Alice Bailly",
				pays: "Lausanne",
				annee: "1926",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK77",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5457",
			licence: "Public Domain Mark 1.0",
			credit: "Federal Art Collection, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Ferdinand Hodler (1853–1918)",
			titre: "Le bûcheron",
			date: "1910",
			dimensions: {
				hauteur: "262",
				longueur: "212",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "src/images/bernmuseum/fK1179_KF100-3793.jpg",
			provenance: {
				nom: "Ferdinand Hodler",
				pays: "Genf",
				annee: "1910",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1179",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9569",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Morgenthaler, Ernst (1887–1962)",
			titre: "Vue depuis la fenêtre",
			date: "1949",
			dimensions: {
				hauteur: "100",
				longueur: "80",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1950",
			image: "src/images/bernmuseum/fK1759.jpg",
			provenance: {
				nom: "Ernst Morgenthaler",
				pays: "Zürich",
				annee: "1949–1950",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1759",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7775",
			licence: "CC BY-NC-ND 3.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Portrait d'un homme à la barbe rougeâtre",
			date: "1880",
			dimensions: {
				hauteur: "44",
				longueur: "36.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1892",
			image: "src/images/bernmuseum/GKS7.jpg",
			provenance: {
				nom: "Nachlass Stauffer-Bern",
				pays: "Biel",
				annee: "1891–1892",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS7",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6435",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Étude sur crâne",
			date: "1880-1881",
			dimensions: {
				hauteur: "29",
				longueur: "40",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1892",
			image: "src/images/bernmuseum/GKS19.jpg",
			provenance: {
				nom: "Nachlass Stauffer-Bern",
				pays: "Biel",
				annee: "1891–1892",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS19",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6436",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Durheim, Johann Ludwig Rudolf (1811–1895)",
			titre: "Femmes sur le rivage du Nil près de Gizeh",
			date: "1849",
			dimensions: {
				hauteur: "23.7",
				longueur: "37.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1895",
			image: "src/images/bernmuseum/GKS129.jpg",
			provenance: {
				nom: "Nachlass Durheim",
				pays: "Bern",
				annee: "1895",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS129",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6442",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Boltraffio, Giovanni Antonio (1467–1516)",
			titre: "Portrait d'un jeune homme",
			date: "vers 1500",
			dimensions: {
				hauteur: "49.3",
				longueur: "40.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1897",
			image: "src/images/bernmuseum/GKS183.jpg",
			provenance: {
				nom: "Eduard von Ernst-Marcuard",
				pays: "Berna",
				annee: "?–1892–1897",
				pour: "Confederazione svizzera",
			},
			numeroinventaire: "GKS183",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6449",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Vigée-Le Brun, Elisabeth (1755–1842)",
			titre: "Fête d´Unspunnen",
			date: "1808-1809",
			dimensions: {
				hauteur: "84",
				longueur: "114",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "src/images/bernmuseum/GKS483.jpg",
			provenance: {
				nom: "Dr. Theodor Engelmann",
				pays: "Bâle",
				annee: "?–1910",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS483",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5565",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/bernmuseum/",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
	],
	baselmuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/baselmuseum/fK1572.jpg",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
	],
	lausannemuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/monimage.jpg",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "",
			lien: "",
			licence: "All rights reserved",
			credit: "",
		},
	],
};
