export const arts = {
	bernmuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/monimage.jpg",
			provenance: {
				nom: "",
				prenom: "",
				pays: "",
				annee: "",
			},
			numeroinventaire: "",
			emplacement: "",
			licence: "All rights reserved",
			credit: "",
		},
	],
	baselmuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/monimage.jpg",
			provenance: {
				nom: "",
				prenom: "",
				pays: "",
				annee: "",
			},
			numeroinventaire: "",
			emplacement: "",
			licence: "All rights reserved",
			credit: "",
		},
	],
	lausannemuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "",
			anneeacquisition: "",
			image: "src/images/monimage.jpg",
			provenance: {
				nom: "",
				prenom: "",
				pays: "",
				annee: "",
			},
			numeroinventaire: "",
			emplacement: "",
			licence: "All rights reserved",
			credit: "",
		},
	],
};
