export const arts = {
	bernmuseum: [
		{
			artiste: "Alice Marie Louise Bailly (1872–1938)",
			titre: "Jeune musicien (Hans Jegerlehner)",
			date: "1926",
			dimensions: {
				hauteur: "34",
				longueur: "65",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1926",
			image: "src/images/bernmuseum/fK77.jpg",
			provenance: {
				nom: "Alice Bailly",
				pays: "Lausanne",
				annee: "1926",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK77",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5457",
			licence: "Public Domain Mark 1.0",
			credit: "Federal Art Collection, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Ferdinand Hodler (1853–1918)",
			titre: "Le bûcheron",
			date: "1910",
			dimensions: {
				hauteur: "262",
				longueur: "212",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "src/images/bernmuseum/fK1179_KF100-3793.jpg",
			provenance: {
				nom: "Ferdinand Hodler",
				pays: "Genf",
				annee: "1910",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1179",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9569",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Morgenthaler, Ernst (1887–1962)",
			titre: "Vue depuis la fenêtre",
			date: "1949",
			dimensions: {
				hauteur: "100",
				longueur: "80",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1950",
			image: "src/images/bernmuseum/fK1759.jpg",
			provenance: {
				nom: "Ernst Morgenthaler",
				pays: "Zürich",
				annee: "1949–1950",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1759",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7775",
			licence: "CC BY-NC-ND 3.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Portrait d'un homme à la barbe rougeâtre",
			date: "1880",
			dimensions: {
				hauteur: "44",
				longueur: "36.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1892",
			image: "src/images/bernmuseum/GKS7.jpg",
			provenance: {
				nom: "Nachlass Stauffer-Bern",
				pays: "Biel",
				annee: "1891–1892",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS7",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6435",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Étude sur crâne",
			date: "1880-1881",
			dimensions: {
				hauteur: "29",
				longueur: "40",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1892",
			image: "src/images/bernmuseum/GKS19.jpg",
			provenance: {
				nom: "Nachlass Stauffer-Bern",
				pays: "Biel",
				annee: "1891–1892",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS19",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6436",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Durheim, Johann Ludwig Rudolf (1811–1895)",
			titre: "Femmes sur le rivage du Nil près de Gizeh",
			date: "1849",
			dimensions: {
				hauteur: "23.7",
				longueur: "37.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1895",
			image: "src/images/bernmuseum/GKS129.jpg",
			provenance: {
				nom: "Nachlass Durheim",
				pays: "Bern",
				annee: "1895",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS129",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6442",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Boltraffio, Giovanni Antonio (1467–1516)",
			titre: "Portrait d'un jeune homme",
			date: "vers 1500",
			dimensions: {
				hauteur: "49.3",
				longueur: "40.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1897",
			image: "src/images/bernmuseum/GKS183.jpg",
			provenance: {
				nom: "Eduard von Ernst-Marcuard",
				pays: "Berna",
				annee: "?–1892–1897",
				pour: "Confederazione svizzera",
			},
			numeroinventaire: "GKS183",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6449",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Vigée-Le Brun, Elisabeth (1755–1842)",
			titre: "Fête d´Unspunnen",
			date: "1808-1809",
			dimensions: {
				hauteur: "84",
				longueur: "114",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "src/images/bernmuseum/GKS483.jpg",
			provenance: {
				nom: "Dr. Theodor Engelmann",
				pays: "Bâle",
				annee: "?–1910",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS483",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5565",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Max Alfred Buri (1868–1915)",
			titre: "Portrait de la fille Hedwig",
			date: "1913",
			dimensions: {
				hauteur: "110",
				longueur: "81",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1917",
			image: "src/images/bernmuseum/GKS528.tif",
			provenance: {
				nom: "Frida Buri-Schenk",
				pays: "Brienz",
				annee: "1915–1917",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS528",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5575",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Max Alfred Buri (1868–1915)",
			titre: "Autoportrait",
			date: "1897",
			dimensions: {
				hauteur: "42",
				longueur: "42",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1919",
			image: "src/images/bernmuseum/GKS551.jpg",
			provenance: {
				nom: "Nachlass Max Buri",
				pays: "München, DE",
				annee: "1915–1919",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS551",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6657",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Ferdinand Hodler (1853–1918)",
			titre: "L'Elu",
			date: "1893-1894",
			dimensions: {
				hauteur: "219",
				longueur: "296",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1920",
			image: "src/images/bernmuseum/GKS590.tif",
			provenance: {
				nom: "Berthe Hodler-Jacques",
				pays: "Genf",
				annee: "1920",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS590",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5580",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Calame, Alexandre (1810–1864)",
			titre: "Le grand Eiger, soleil levant",
			date: "1844",
			dimensions: {
				hauteur: "106.2",
				longueur: "139.9",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1921",
			image: "src/images/bernmuseum/GKS595.tif",
			provenance: {
				nom: " Frank Puaux",
				pays: "Paris",
				annee: "?–1921",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS595",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5582",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Breslau, Louise Catherine (1856–1927)",
			titre: "Le thé de cinq heure",
			date: "1883",
			dimensions: {
				hauteur: "150.5",
				longueur: "151.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1925",
			image: "src/images/bernmuseum/GKS653.jpg",
			provenance: {
				nom: "Louise Catherine Breslau",
				pays: "Neuilly sur-Seine, FR",
				annee: "1883–1925",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS653",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6665",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Auguste Baud-Bovy (1848–1899)",
			titre: "Portrait du peintre Albert Gos",
			date: "1879",
			dimensions: {
				hauteur: "113.7",
				longueur: "85.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1930",
			image: "src/images/bernmuseum/GKS726.jpg",
			provenance: {
				nom: "Exposition de mémoire Auguste Baud-Bovy",
				pays: "Kunsthaus Zurich",
				annee: "20.2.–19.3.1930",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS726",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6673",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Inconnu / Unbekannt / Ignoto",
			titre: "Autel des trépassés",
			date: "1505",
			dimensions: {
				hauteur: "149",
				longueur: "62",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "",
			image: "src/images/bernmuseum/GKS810_Werktag.jpg",
			provenance: {
				nom: "Théodora de Saussure/de la Rive",
				pays: "Genthod/GE",
				annee: "1882–1935",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS810/1-2",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9649",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Niklaus (Niclaus) (I.) Manuel, genannt Deutsch (1484–1530)",
			titre: "Saint Antoine tenté par la femme",
			date: "1518 - 1520",
			dimensions: {
				hauteur: "101",
				longueur: "126",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1936",
			image: "src/images/bernmuseum/GKS855_GKS200-112.jpg",
			provenance: {
				nom: "Comtesse Hedwige Rey (geb. Branicki)",
				pays: "Indre-et-Loire, FR",
				annee: "?–1936",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS855",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9640",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Manuel, genannt Deutsch, Niklaus (Niclaus) (I.) (1484–1530)",
			titre: "Saint Antoine soigne les malades et les possédés",
			date: "1518-1520",
			dimensions: {
				hauteur: "101",
				longueur: "126",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1936",
			image: "src/images/bernmuseum/GKS856.jpg",
			provenance: {
				nom: "Comtesse Hedwige Rey (geb. Branicki)",
				pays: "Indre-et-Loire, FR",
				annee: "?–1936",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS856",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6684",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Inconnu / Unbekannt / Ignoto",
			titre: "Saint Béat avec le dragon",
			date: "vers 1520",
			dimensions: {
				hauteur: "136",
				longueur: "75",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1937",
			image: "src/images/bernmuseum/GKS865_GKS200-1889_Vorderseite.JPG",
			provenance: {
				nom: "Galerie Otto Schatzker",
				pays: "Wien",
				annee: "?−1937",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS865",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8828",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Anker, Albert (1831–1910)",
			titre: "La crêche en promenade sur le pont de Kirchenfeld à Berne",
			date: "1900",
			dimensions: {
				hauteur: "76",
				longueur: "127",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1944",
			image: "src/images/bernmuseum/GKS915.tif",
			provenance: {
				nom: "Dr. Fritz Nathan",
				pays: "St. Gallen",
				annee: "?–1944",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS915",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5619",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Barthélemy Menn (1815–1893)",
			titre: "Jeune fille au bord d'un lac",
			date: "avant 1893",
			dimensions: {
				hauteur: "30.4",
				longueur: "43.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1947",
			image: "src/images/bernmuseum/GKS937_Vorderseite_G1638.jpg",
			provenance: {
				nom: "Oskar Reinhart",
				pays: "Winterthour",
				annee: "?–1947",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS937",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9643",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Plepp (1595–1642)",
			titre: "Nature morte avec Salade, cerises, fromage et verre de vin",
			date: "1632",
			dimensions: {
				hauteur: "37",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1948",
			image: "src/images/bernmuseum/GKS941_GKS200-120.jpg",
			provenance: {
				nom: "Galerie Theodor Fischer",
				pays: "Luzern",
				annee: "1948",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS941",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9644",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Plepp (1595–1642)",
			titre: "Nature morte avec cerises et framboises",
			date: "1615 - 1642",
			dimensions: {
				hauteur: "32.5",
				longueur: "55.8",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1953",
			image: "src/images/bernmuseum/GKS985_Vorderseite_G1766.jpg",
			provenance: {
				nom: "Adine Ganzoni",
				pays: "Genf",
				annee: "?–1953",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS985",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9671",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Heintz der Ältere (1564–1609)",
			titre: "Portrait d'Albrecht Fugger von Kirchberg und Weissenhorn",
			date: "1598",
			dimensions: {
				hauteur: "87",
				longueur: "69",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1955",
			image: "src/images/bernmuseum/GKS998_Vorderseite_G1816.jpg",
			provenance: {
				nom: "The Arcade Gallery Ltd.",
				pays: "London",
				annee: "1955",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS998",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9680",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Heintz der Ältere (1564–1609)",
			titre: "Portrait de Veronika Fugger",
			date: "1598",
			dimensions: {
				hauteur: "87",
				longueur: "70",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1955",
			image: "src/images/bernmuseum/GKS999_GKS200-127.jpg",
			provenance: {
				nom: "The Arcade Gallery Ltd.",
				pays: "London",
				annee: "1955",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS999",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8915",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Wolfgang Adam Töpffer (1766–1847)",
			titre:
				"Paysage et scène de genre devant le Mont-Blanc depuis le moulin de la Fayet",
			date: "1815",
			dimensions: {
				hauteur: "87.5",
				longueur: "69",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1964s",
			image: "src/images/bernmuseum/GKS1054_GKS200-137.jpg",
			provenance: {
				nom: "Dr. Fritz Nathan",
				pays: "Zurich",
				annee: "1964",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1054",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8997",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Cuno Amiet (1868–1961)",
			titre: "Le peintre en plein air",
			date: "1916",
			dimensions: {
				hauteur: "48",
				longueur: "42",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1967",
			image: "src/images/bernmuseum/GKS1066-57_Vorderseite_A 9462.jpg",
			provenance: {
				nom: "Dr. Marguerite Schuler",
				pays: "Muri/BE",
				annee: "1967",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1066/57",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9687",
			licence: "All rights reserved",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Anker, Albert (1831–1910)",
			titre: "Bière et radis",
			date: "1898",
			dimensions: {
				hauteur: "32.8",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1961",
			image: "src/images/bernmuseum/GKS1098.jpg",
			provenance: {
				nom: "Marie-Charlotte Quinche",
				pays: "Neuenburg",
				annee: "?–1961",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1098",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5677",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden (1885–1933)",
			titre: "Ange à tête inclinée",
			date: "1908-1912",
			dimensions: {
				hauteur: "24",
				longueur: "16",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1975",
			image: "src/images/bernmuseum/GKS1107.jpg",
			provenance: {
				nom: "Galerie Kurt Meissner",
				pays: "Zürich",
				annee: "1955–1975",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1107",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8132",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden (1885–1933)",
			titre: "Jeune fille assise dans une robe d'été blanche",
			date: "1900 - 1933",
			dimensions: {
				hauteur: "24",
				longueur: "16",
				profondeur: "",
			},
			objet: "Dessin",
			anneeacquisition: "1975",
			image: "src/images/bernmuseum/GKS1109_Vorderseite_A9148.jpg",
			provenance: {
				nom: "Galerie Kurt Meissner",
				pays: "Zürich",
				annee: "1955–1975",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1109",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9702",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden (1885–1933)",
			titre: "Putti d'après Raphaël, Miniature",
			date: "avant 1906",
			dimensions: {
				hauteur: "3",
				longueur: "5.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1976",
			image: "src/images/bernmuseum/GKS1119-3_Vorderseite_A9197.jpg",
			provenance: {
				nom: "Galerie Feilchenfeldt",
				pays: "Zürich",
				annee: "?–1976",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1119/3",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9707",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Louis René Moilliet (1880–1962)",
			titre: "Portrait de Cécile",
			date: "1913",
			dimensions: {
				hauteur: "46",
				longueur: "38",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1986",
			image: "src/images/bernmuseum/GKS1176_GKS200-156.jpg",
			provenance: {
				nom: "Claire (Kay) Oederlin",
				pays: "La Tour-de-Peilz/VD",
				annee: "1962–1986",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1176",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9646",
			licence: "All rights reserved",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Albert Anker (1831–1910)",
			titre: "Albert Anker (1831–1910)",
			date: "1890 - 1910",
			dimensions: {
				hauteur: "32.7",
				longueur: "25.3",
				profondeur: "",
			},
			objet: "Dessin",
			anneeacquisition: "1989",
			image: "src/images/bernmuseum/GKS1213_Vorderseite_A1989.282.jpg",
			provenance: {
				nom: "Joseph Georges und Margot Bloch",
				pays: "Zürich",
				annee: "?–1989",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1213",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9647",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Portrait du constructeur Oscar Titz",
			date: "1883",
			dimensions: {
				hauteur: "126.5",
				longueur: "90.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1991",
			image: "src/images/bernmuseum/GKS1225_GKS200-218_ungerahmt.jpg",
			provenance: {
				nom: "Robert Cavegn",
				pays: "Felsburg, DE",
				annee: "1989–1991",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1225",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9260",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Werner d. J. (1637–1710)",
			titre:
				"Ulysse démasque Achille déguisé en jeune femme, dans le palais du roi Lycomède",
			date: "1678",
			dimensions: {
				hauteur: "75",
				longueur: "61",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1992",
			image: "src/images/bernmuseum/GKS1232_GKS200-713.jpg",
			provenance: {
				nom: "Galerie Römer",
				pays: "Zürich",
				annee: "1991–1992",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1232",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9264",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Karl Durheim (1810–1890)",
			titre:
				"Portrait de Albert Anker avec Friedrich Fetscherin (à gauche) et August Lörtscher (à droite), deux amis de Tübingen",
			date: "1853",
			dimensions: {
				hauteur: "10.8",
				longueur: "16.2",
				profondeur: "",
			},
			objet: "Photographie",
			anneeacquisition: "2000",
			image: "src/images/bernmuseum/GKS1279_GKS200-1773.jpg",
			provenance: {
				nom: "Peter Herzog",
				pays: "Basel",
				annee: "?–2000",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1279",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/930",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Giovanni Ulrico Giacometti (1868–1933)",
			titre: "Enfants au soleil",
			date: "1910",
			dimensions: {
				hauteur: "91.3",
				longueur: "100",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "2000",
			image: "src/images/bernmuseum/GKS1282_GKS200-714.jpg",
			provenance: {
				nom: "Christie's",
				pays: "Zurigo",
				annee: "2000",
				pour: "Confederazione Svizzera",
			},
			numeroinventaire: "GKS1282",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9304",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
	],
	baselmuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "",
			image: "src/images/baselmuseum/fK1572.jpg",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "Kunstmuseum Bern",
			lien: "",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
	],
	lausannemuseum: [
		{
			artiste: "",
			titre: "",
			date: "",
			dimensions: {
				hauteur: "",
				longueur: "",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "",
			image: "src/images/monimage.jpg",
			provenance: {
				nom: "",
				pays: "",
				annee: "",
				pour: "",
			},
			numeroinventaire: "",
			emplacement: "Kunstmuseum Bern",
			lien: "",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
	],
};
