export const arts = {
	bernmuseum: [
		{
			artiste: "Alice Marie Louise Bailly (1872–1938)",
			titre: "Jeune musicien (Hans Jegerlehner)",
			date: "1926",
			dimensions: {
				hauteur: "34",
				longueur: "65",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1926",
			image: "/assets/images/bernmuseum/fK77.jpg",
			provenance: {
				nom: "Alice Bailly",
				pays: "Lausanne",
				annee: "1926",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK77",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5457",
			licence: "Public Domain Mark 1.0",
			credit: "Federal Art Collection, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Ferdinand Hodler (1853–1918)",
			titre: "Le bûcheron",
			date: "1910",
			dimensions: {
				hauteur: "262",
				longueur: "212",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "/assets/images/bernmuseum/fK1179_KF100-3793.jpg",
			provenance: {
				nom: "Ferdinand Hodler",
				pays: "Genf",
				annee: "1910",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1179",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9569",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Morgenthaler, Ernst (1887–1962)",
			titre: "Vue depuis la fenêtre",
			date: "1949",
			dimensions: {
				hauteur: "100",
				longueur: "80",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1950",
			image: "/assets/images/bernmuseum/fK1759.jpg",
			provenance: {
				nom: "Ernst Morgenthaler",
				pays: "Zürich",
				annee: "1949–1950",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1759",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7775",
			licence: "CC BY-NC-ND 3.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Portrait d'un homme à la barbe rougeâtre",
			date: "1880",
			dimensions: {
				hauteur: "44",
				longueur: "36.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1892",
			image: "/assets/images/bernmuseum/GKS7.jpg",
			provenance: {
				nom: "Nachlass Stauffer-Bern",
				pays: "Biel",
				annee: "1891–1892",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS7",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6435",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Étude sur crâne",
			date: "1880-1881",
			dimensions: {
				hauteur: "29",
				longueur: "40",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1892",
			image: "/assets/images/bernmuseum/GKS19.jpg",
			provenance: {
				nom: "Nachlass Stauffer-Bern",
				pays: "Biel",
				annee: "1891–1892",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS19",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6436",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Durheim, Johann Ludwig Rudolf (1811–1895)",
			titre: "Femmes sur le rivage du Nil près de Gizeh",
			date: "1849",
			dimensions: {
				hauteur: "23.7",
				longueur: "37.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1895",
			image: "/assets/images/bernmuseum/GKS129.jpg",
			provenance: {
				nom: "Nachlass Durheim",
				pays: "Bern",
				annee: "1895",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS129",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6442",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Boltraffio, Giovanni Antonio (1467–1516)",
			titre: "Portrait d'un jeune homme",
			date: "vers 1500",
			dimensions: {
				hauteur: "49.3",
				longueur: "40.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1897",
			image: "/assets/images/bernmuseum/GKS183.jpg",
			provenance: {
				nom: "Eduard von Ernst-Marcuard",
				pays: "Berna",
				annee: "?–1892–1897",
				pour: "Confederazione svizzera",
			},
			numeroinventaire: "GKS183",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6449",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Vigée-Le Brun, Elisabeth (1755–1842)",
			titre: "Fête d´Unspunnen",
			date: "1808-1809",
			dimensions: {
				hauteur: "84",
				longueur: "114",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "/assets/images/bernmuseum/GKS483.jpg",
			provenance: {
				nom: "Dr. Theodor Engelmann",
				pays: "Bâle",
				annee: "?–1910",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS483",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5565",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Max Alfred Buri (1868–1915)",
			titre: "Portrait de la fille Hedwig",
			date: "1913",
			dimensions: {
				hauteur: "110",
				longueur: "81",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1917",
			image: "/assets/images/bernmuseum/GKS528.jpg",
			provenance: {
				nom: "Frida Buri-Schenk",
				pays: "Brienz",
				annee: "1915–1917",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS528",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5575",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Max Alfred Buri (1868–1915)",
			titre: "Autoportrait",
			date: "1897",
			dimensions: {
				hauteur: "42",
				longueur: "42",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1919",
			image: "/assets/images/bernmuseum/GKS551.jpg",
			provenance: {
				nom: "Nachlass Max Buri",
				pays: "München, DE",
				annee: "1915–1919",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS551",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6657",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Ferdinand Hodler (1853–1918)",
			titre: "L'Elu",
			date: "1893-1894",
			dimensions: {
				hauteur: "219",
				longueur: "296",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1920",
			image: "/assets/images/bernmuseum/GKS590.jpg",
			provenance: {
				nom: "Berthe Hodler-Jacques",
				pays: "Genf",
				annee: "1920",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS590",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5580",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Calame, Alexandre (1810–1864)",
			titre: "Le grand Eiger, soleil levant",
			date: "1844",
			dimensions: {
				hauteur: "106.2",
				longueur: "139.9",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1921",
			image: "/assets/images/bernmuseum/GKS595.jpg",
			provenance: {
				nom: " Frank Puaux",
				pays: "Paris",
				annee: "?–1921",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS595",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5582",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Breslau, Louise Catherine (1856–1927)",
			titre: "Le thé de cinq heure",
			date: "1883",
			dimensions: {
				hauteur: "150.5",
				longueur: "151.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1925",
			image: "/assets/images/bernmuseum/GKS653.jpg",
			provenance: {
				nom: "Louise Catherine Breslau",
				pays: "Neuilly sur-Seine, FR",
				annee: "1883–1925",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS653",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6665",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Auguste Baud-Bovy (1848–1899)",
			titre: "Portrait du peintre Albert Gos",
			date: "1879",
			dimensions: {
				hauteur: "113.7",
				longueur: "85.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1930",
			image: "/assets/images/bernmuseum/GKS726.jpg",
			provenance: {
				nom: "Exposition de mémoire Auguste Baud-Bovy",
				pays: "Kunsthaus Zurich",
				annee: "20.2.–19.3.1930",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS726",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6673",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Inconnu / Unbekannt / Ignoto",
			titre: "Autel des trépassés",
			date: "1505",
			dimensions: {
				hauteur: "149",
				longueur: "62",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "",
			image: "/assets/images/bernmuseum/GKS810_Werktag.jpg",
			provenance: {
				nom: "Théodora de Saussure/de la Rive",
				pays: "Genthod/GE",
				annee: "1882–1935",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS810/1-2",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9649",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Niklaus (Niclaus) (I.) Manuel, genannt Deutsch (1484–1530)",
			titre: "Saint Antoine tenté par la femme",
			date: "1518 - 1520",
			dimensions: {
				hauteur: "101",
				longueur: "126",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1936",
			image: "/assets/images/bernmuseum/GKS855_GKS200-112.jpg",
			provenance: {
				nom: "Comtesse Hedwige Rey (geb. Branicki)",
				pays: "Indre-et-Loire, FR",
				annee: "?–1936",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS855",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9640",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Manuel, genannt Deutsch, Niklaus (Niclaus) (I.) (1484–1530)",
			titre: "Saint Antoine soigne les malades et les possédés",
			date: "1518-1520",
			dimensions: {
				hauteur: "101",
				longueur: "126",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1936",
			image: "/assets/images/bernmuseum/GKS856.jpg",
			provenance: {
				nom: "Comtesse Hedwige Rey (geb. Branicki)",
				pays: "Indre-et-Loire, FR",
				annee: "?–1936",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS856",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6684",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Inconnu / Unbekannt / Ignoto",
			titre: "Saint Béat avec le dragon",
			date: "vers 1520",
			dimensions: {
				hauteur: "136",
				longueur: "75",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1937",
			image: "/assets/images/bernmuseum/GKS865_GKS200-1889_Vorderseite.JPG",
			provenance: {
				nom: "Galerie Otto Schatzker",
				pays: "Wien",
				annee: "?−1937",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS865",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8828",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern, Bern",
		},
		{
			artiste: "Anker, Albert (1831–1910)",
			titre: "La crêche en promenade sur le pont de Kirchenfeld à Berne",
			date: "1900",
			dimensions: {
				hauteur: "76",
				longueur: "127",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1944",
			image: "/assets/images/bernmuseum/GKS915.jpg",
			provenance: {
				nom: "Dr. Fritz Nathan",
				pays: "St. Gallen",
				annee: "?–1944",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS915",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5619",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Barthélemy Menn (1815–1893)",
			titre: "Jeune fille au bord d'un lac",
			date: "avant 1893",
			dimensions: {
				hauteur: "30.4",
				longueur: "43.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1947",
			image: "/assets/images/bernmuseum/GKS937_Vorderseite_G1638.jpg",
			provenance: {
				nom: "Oskar Reinhart",
				pays: "Winterthour",
				annee: "?–1947",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS937",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9643",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Plepp (1595–1642)",
			titre: "Nature morte avec Salade, cerises, fromage et verre de vin",
			date: "1632",
			dimensions: {
				hauteur: "37",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1948",
			image: "/assets/images/bernmuseum/GKS941_GKS200-120.jpg",
			provenance: {
				nom: "Galerie Theodor Fischer",
				pays: "Luzern",
				annee: "1948",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS941",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9644",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Plepp (1595–1642)",
			titre: "Nature morte avec cerises et framboises",
			date: "1615 - 1642",
			dimensions: {
				hauteur: "32.5",
				longueur: "55.8",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1953",
			image: "/assets/images/bernmuseum/GKS985_Vorderseite_G1766.jpg",
			provenance: {
				nom: "Adine Ganzoni",
				pays: "Genf",
				annee: "?–1953",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS985",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9671",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Heintz der Ältere (1564–1609)",
			titre: "Portrait d'Albrecht Fugger von Kirchberg und Weissenhorn",
			date: "1598",
			dimensions: {
				hauteur: "87",
				longueur: "69",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1955",
			image: "/assets/images/bernmuseum/GKS998_Vorderseite_G1816.jpg",
			provenance: {
				nom: "The Arcade Gallery Ltd.",
				pays: "London",
				annee: "1955",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS998",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9680",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Heintz der Ältere (1564–1609)",
			titre: "Portrait de Veronika Fugger",
			date: "1598",
			dimensions: {
				hauteur: "87",
				longueur: "70",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1955",
			image: "/assets/images/bernmuseum/GKS999_GKS200-127.jpg",
			provenance: {
				nom: "The Arcade Gallery Ltd.",
				pays: "London",
				annee: "1955",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS999",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8915",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Wolfgang Adam Töpffer (1766–1847)",
			titre:
				"Paysage et scène de genre devant le Mont-Blanc depuis le moulin de la Fayet",
			date: "1815",
			dimensions: {
				hauteur: "87.5",
				longueur: "69",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1964s",
			image: "/assets/images/bernmuseum/GKS1054_GKS200-137.jpg",
			provenance: {
				nom: "Dr. Fritz Nathan",
				pays: "Zurich",
				annee: "1964",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1054",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8997",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Cuno Amiet (1868–1961)",
			titre: "Le peintre en plein air",
			date: "1916",
			dimensions: {
				hauteur: "48",
				longueur: "42",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1967",
			image: "/assets/images/bernmuseum/GKS1066-57_Vorderseite_A 9462.jpg",
			provenance: {
				nom: "Dr. Marguerite Schuler",
				pays: "Muri/BE",
				annee: "1967",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1066/57",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9687",
			licence: "All rights reserved",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Anker, Albert (1831–1910)",
			titre: "Bière et radis",
			date: "1898",
			dimensions: {
				hauteur: "32.8",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1961",
			image: "/assets/images/bernmuseum/GKS1098.jpg",
			provenance: {
				nom: "Marie-Charlotte Quinche",
				pays: "Neuenburg",
				annee: "?–1961",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1098",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5677",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden (1885–1933)",
			titre: "Ange à tête inclinée",
			date: "1908-1912",
			dimensions: {
				hauteur: "24",
				longueur: "16",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1975",
			image: "/assets/images/bernmuseum/GKS1107.jpg",
			provenance: {
				nom: "Galerie Kurt Meissner",
				pays: "Zürich",
				annee: "1955–1975",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1107",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8132",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden (1885–1933)",
			titre: "Jeune fille assise dans une robe d'été blanche",
			date: "1900 - 1933",
			dimensions: {
				hauteur: "24",
				longueur: "16",
				profondeur: "",
			},
			objet: "Dessin",
			anneeacquisition: "1975",
			image: "/assets/images/bernmuseum/GKS1109_Vorderseite_A9148.jpg",
			provenance: {
				nom: "Galerie Kurt Meissner",
				pays: "Zürich",
				annee: "1955–1975",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1109",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9702",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden (1885–1933)",
			titre: "Putti d'après Raphaël, Miniature",
			date: "avant 1906",
			dimensions: {
				hauteur: "3",
				longueur: "5.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1976",
			image: "/assets/images/bernmuseum/GKS1119-3_Vorderseite_A9197.jpg",
			provenance: {
				nom: "Galerie Feilchenfeldt",
				pays: "Zürich",
				annee: "?–1976",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1119/3",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9707",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Louis René Moilliet (1880–1962)",
			titre: "Portrait de Cécile",
			date: "1913",
			dimensions: {
				hauteur: "46",
				longueur: "38",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1986",
			image: "/assets/images/bernmuseum/GKS1176_GKS200-156.jpg",
			provenance: {
				nom: "Claire (Kay) Oederlin",
				pays: "La Tour-de-Peilz/VD",
				annee: "1962–1986",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1176",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9646",
			licence: "All rights reserved",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Albert Anker (1831–1910)",
			titre: "Jeune fille tricotant",
			date: "1890 - 1910",
			dimensions: {
				hauteur: "32.7",
				longueur: "25.3",
				profondeur: "",
			},
			objet: "Dessin",
			anneeacquisition: "1989",
			image: "/assets/images/bernmuseum/GKS1213_Vorderseite_A1989.282.jpg",
			provenance: {
				nom: "Joseph Georges und Margot Bloch",
				pays: "Zürich",
				annee: "?–1989",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1213",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9647",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Karl Stauffer-Bern (1857–1891)",
			titre: "Portrait du constructeur Oscar Titz",
			date: "1883",
			dimensions: {
				hauteur: "126.5",
				longueur: "90.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1991",
			image: "/assets/images/bernmuseum/GKS1225_GKS200-218_ungerahmt.jpg",
			provenance: {
				nom: "Robert Cavegn",
				pays: "Felsburg, DE",
				annee: "1989–1991",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1225",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9260",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Joseph Werner d. J. (1637–1710)",
			titre:
				"Ulysse démasque Achille déguisé en jeune femme, dans le palais du roi Lycomède",
			date: "1678",
			dimensions: {
				hauteur: "75",
				longueur: "61",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1992",
			image: "/assets/images/bernmuseum/GKS1232_GKS200-713.jpg",
			provenance: {
				nom: "Galerie Römer",
				pays: "Zürich",
				annee: "1991–1992",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1232",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9264",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Karl Durheim (1810–1890)",
			titre:
				"Portrait de Albert Anker avec Friedrich Fetscherin (à gauche) et August Lörtscher (à droite), deux amis de Tübingen",
			date: "1853",
			dimensions: {
				hauteur: "10.8",
				longueur: "16.2",
				profondeur: "",
			},
			objet: "Photographie",
			anneeacquisition: "2000",
			image: "/assets/images/bernmuseum/GKS1279_GKS200-1773.jpg",
			provenance: {
				nom: "Peter Herzog",
				pays: "Basel",
				annee: "?–2000",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1279",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/930",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
		{
			artiste: "Giovanni Ulrico Giacometti (1868–1933)",
			titre: "Enfants au soleil",
			date: "1910",
			dimensions: {
				hauteur: "91.3",
				longueur: "100",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "2000",
			image: "/assets/images/bernmuseum/GKS1282_GKS200-714.jpg",
			provenance: {
				nom: "Christie's",
				pays: "Zurigo",
				annee: "2000",
				pour: "Confederazione Svizzera",
			},
			numeroinventaire: "GKS1282",
			emplacement: "Kunstmuseum Bern",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9304",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Bern",
		},
	],
	baselmuseum: [
		{
			artiste: "Hans Berger (1882–1977)",
			titre: "La Bachette",
			date: "1934",
			dimensions: {
				hauteur: "130",
				longueur: "170",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1934",
			image: "/assets/images/baselmuseum/fk191_KF200-11086_ungerahmt.JPG",
			provenance: {
				nom: "Hans Berger",
				pays: "Genf",
				annee: "1934",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK191",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9557",
			licence: "All rights reserved",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Giacometti, Giovanni Ulrico (1868–1933)",
			titre: "Paysage d'automne",
			date: "1927",
			dimensions: {
				hauteur: "101",
				longueur: "105.3",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1928",
			image: "/assets/images/baselmuseum/fK930.jpg",
			provenance: {
				nom: "Giovanni Ulrico Giacometti",
				pays: "Stampa/GR",
				annee: "1927–1928",
				pour: "Confederazione svizzera",
			},
			numeroinventaire: "fK930",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7014",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Martin, Eugène Louis",
			titre: "Le viaduc",
			date: "1937",
			dimensions: {
				hauteur: "60",
				longueur: "73",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1938",
			image: "/assets/images/baselmuseum/fK1572.jpg",
			provenance: {
				nom: "Eugène Martin",
				pays: "Genève",
				annee: "1937–1938",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK1572",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5879",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Meyer-Amden, Otto Friedrich",
			titre: "Paysage d'étoiles, chaîne de montagne",
			date: "1931",
			dimensions: {
				hauteur: "100.5",
				longueur: "101",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1933",
			image: "/assets/images/baselmuseum/fK1707.jpg",
			provenance: {
				nom: "Otto Meyer-Amden",
				pays: "Zürich",
				annee: "1931–1933",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1707",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5891",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Meyer-Amden, Otto Friedrich",
			titre: "Lac de Walenstadt de nuit",
			date: "1931",
			dimensions: {
				hauteur: "100",
				longueur: "125",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1933",
			image: "/assets/images/baselmuseum/fK1708.jpg",
			provenance: {
				nom: "Otto Meyer-Amden",
				pays: "Zürich",
				annee: "1931–1933",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1708",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5892",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Karl Stauffer-Bern",
			titre: "Portrait de Gustav Freytag",
			date: "1886",
			dimensions: {
				hauteur: "41.5",
				longueur: "31",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1896",
			image: "/assets/images/baselmuseum/fK2353.jpg",
			provenance: {
				nom: "Karl Stauffer-Bern",
				pays: "Berlin",
				annee: "1886–1891",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK2353",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5965",
			licence: "Public Domain Mark 1.0",
			credit: "Federal Art Collection, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Feuerbach, Anselm",
			titre: "La mort de Pierre l'Arétin",
			date: "1854",
			dimensions: {
				hauteur: "267.5",
				longueur: "176.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1895",
			image: "/assets/images/baselmuseum/GKS118.jpg",
			provenance: {
				nom: "Anselm Feuerbach",
				pays: "München",
				annee: "1854",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS118",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7483",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Cuyp, Aelbert Jacobsz",
			titre: "Officier avec cheval",
			date: "1640",
			dimensions: {
				hauteur: "36",
				longueur: "48",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1896",
			image: "/assets/images/baselmuseum/GKS165.jpg",
			provenance: {
				nom: "Aelbert Jacobsz, Cuyp",
				pays: "Dordrecht, NL",
				annee: "1640",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS165",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7484",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Salzburger, Meister",
			titre: "La crucifixion du Christ",
			date: "1470",
			dimensions: {
				hauteur: "215.5",
				longueur: "89.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1896",
			image: "/assets/images/baselmuseum/GKS181.jpg",
			provenance: {
				nom: "Unbekannter Meister, Salzburg",
				pays: "Basel",
				annee: "1896",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS181",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6448",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Holbein, Ambrosius",
			titre: "Portrait de Hans Herbst (Herbster)",
			date: "1516",
			dimensions: {
				hauteur: "39.5",
				longueur: "26.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1899",
			image: "/assets/images/baselmuseum/GKS208.jpg",
			provenance: {
				nom: "Ambrosius Holbein",
				pays: "Basel",
				annee: "1516",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS208",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5546",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Oberrheinische Schule",
			titre: "12 scènes de la Passion du Christ",
			date: "1425-1450",
			dimensions: {
				hauteur: "111.8",
				longueur: "128",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1899",
			image: "/assets/images/baselmuseum/GKS211.jpg",
			provenance: {
				nom: "Oberrheinische Schule",
				pays: "DE",
				annee: "1425–1450",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS211",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6452",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Monogrammist H F",
			titre: "Portrait d'un jeune homme",
			date: "1524",
			dimensions: {
				hauteur: "49.5",
				longueur: "38",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1900",
			image: "/assets/images/baselmuseum/GKS227.jpg",
			provenance: {
				nom: "Monogrammist H F",
				pays: "Basel",
				annee: "1524",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS227",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5550",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Holbein, Ambrosius",
			titre: "Portrait idéalisé de l'empereur Justinien",
			date: "1514-1515",
			dimensions: {
				hauteur: "69.5",
				longueur: "68",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1900",
			image: "/assets/images/baselmuseum/GKS228.jpg",
			provenance: {
				nom: "Ambrosius Holbein",
				pays: "Basel",
				annee: "1514/1515",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS228",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5551",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Troy de, Jean François",
			titre: "Diane et Actéon",
			date: "1734",
			dimensions: {
				hauteur: "131.5",
				longueur: "196.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1900",
			image: "/assets/images/baselmuseum/GKS230.jpg",
			provenance: {
				nom: "Jean-François de Troy",
				pays: "Paris, FR",
				annee: "1734",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS230",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5552",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "Portrait de Jakob Mähly comme étudiant",
			date: "1848",
			dimensions: {
				hauteur: "32.5",
				longueur: "24.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1901",
			image: "/assets/images/baselmuseum/GKS281.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Basel",
				annee: "1848",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS281",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7485",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "Tête d'un Romain",
			date: "1863",
			dimensions: {
				hauteur: "46.5",
				longueur: "36.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1901",
			image: "/assets/images/baselmuseum/GKS282.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Florenz",
				annee: "1863",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS282",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7486",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "La peste",
			date: "1897-1898",
			dimensions: {
				hauteur: "30.9",
				longueur: "22.5",
				profondeur: "",
			},
			objet: "Dessin",
			anneeacquisition: "1901",
			image: "/assets/images/baselmuseum/GKS284.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "San Domenico, IT ",
				annee: "1898–1901",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS284",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6455",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Sandreuter Hans",
			titre: "Forêt de châtaigniers à Bignasco",
			date: "1896",
			dimensions: {
				hauteur: "96",
				longueur: "147.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1902",
			image: "/assets/images/baselmuseum/GKS322.jpg",
			provenance: {
				nom: "Hans Sandreuter",
				pays: "Basel",
				annee: "1896–1901",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS322",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6459",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "Une groupe d'arbres au bord de la rivière",
			date: "1851",
			dimensions: {
				hauteur: "15.7",
				longueur: "20.9",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1902",
			image: "/assets/images/baselmuseum/GKS331.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Basel",
				annee: "1851",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS331",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6462",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Kick Simon",
			titre: "Officier et soldats dans des quartiers inconnus",
			date: "1645-1650",
			dimensions: {
				hauteur: "72",
				longueur: "71",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1902",
			image: "/assets/images/baselmuseum/GKS335.jpg",
			provenance: {
				nom: "Simon Kick",
				pays: "Amsterdam",
				annee: "1645/1650",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS335",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8063",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Hess Hieronymus",
			titre: "L'assassinat du roi Albrecht",
			date: "1829",
			dimensions: {
				hauteur: "44",
				longueur: "44",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1903",
			image: "/assets/images/baselmuseum/GKS342.jpg",
			provenance: {
				nom: "Hieronymus Hess",
				pays: "Basel",
				annee: "1829",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS342",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6464",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Giovanni Segantini",
			titre: "À l'abreuvoir (vaches au joug)",
			date: "1888",
			dimensions: {
				hauteur: "84.1",
				longueur: "141.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1904",
			image: "/assets/images/baselmuseum/GKS344.jpg",
			provenance: {
				nom: "Giovanni Segantini",
				pays: "Savognin",
				annee: "1888",
				pour: "Confederazione svizzera",
			},
			numeroinventaire: "GKS344",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5560",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Kunstmuseum Basel",
		},
		{
			artiste: "Flinck Govaert",
			titre: "Golgatha",
			date: "1649",
			dimensions: {
				hauteur: "119",
				longueur: "90",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1904",
			image: "/assets/images/baselmuseum/GKS347.jpg",
			provenance: {
				nom: "Govaert Flinck",
				pays: "Amsterdam",
				annee: "1649",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS347",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6465",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Baldung Hans",
			titre: "La Sainte Anne trinitaire",
			date: "1512-1513",
			dimensions: {
				hauteur: "70",
				longueur: "48.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1909",
			image: "/assets/images/baselmuseum/GKS477.jpg",
			provenance: {
				nom: "Hans Baldung",
				pays: "Freiburg",
				annee: "1512/13",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS477",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6474",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Basler Schule",
			titre: "Volet d'autel gauche, à l'intérieur: Saint Antoine",
			date: "1500-1599",
			dimensions: {
				hauteur: "131.5",
				longueur: "48.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "/assets/images/baselmuseum/GKS491.jpg",
			provenance: {
				nom: "Basler Schule",
				pays: "Kirchgemeinde Büsserach",
				annee: "1910",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS491",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6650",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Basler Schule",
			titre: "Volet d'autel droit, à l'intérieur: saint Christophe",
			date: "1500-1599",
			dimensions: {
				hauteur: "131.5",
				longueur: "49",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1910",
			image: "/assets/images/baselmuseum/GKS492.jpg",
			provenance: {
				nom: "Basler Schule",
				pays: "Kirchgemeinde Büsserach",
				annee: "1910",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS492",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6651",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "Le printemps",
			date: "1862",
			dimensions: {
				hauteur: "33.5",
				longueur: "57",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1917",
			image: "/assets/images/baselmuseum/GKS525.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Basel",
				annee: "1862",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS525",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5574",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "Autoportrait",
			date: "1861",
			dimensions: {
				hauteur: "39.5",
				longueur: "31",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1917",
			image: "/assets/images/baselmuseum/GKS526_GKS200-1102.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Weimar",
				annee: "1861–1901",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS526",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9636",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Martin P. Bühler",
		},
		{
			artiste: "Hess Hieronymus",
			titre:
				"Donner à manger aux affamés – Donner à boire à ceux qui ont soif. Sainte Élisabeth de Hongrie",
			date: "1846",
			dimensions: {
				hauteur: "53",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1919",
			image: "/assets/images/baselmuseum/GKS579-1.jpg",
			provenance: {
				nom: "Hieronymus Hess",
				pays: "Basel",
				annee: "1846",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS579/1",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7494",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Basel",
		},
		{
			artiste: "Hess Hieronymus",
			titre: "Accueillir les pèlerins. Jean de Leyde abrite Albrecht Dürer",
			date: "1846",
			dimensions: {
				hauteur: "53",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1919",
			image: "/assets/images/baselmuseum/GKS579-2.jpg",
			provenance: {
				nom: "Hieronymus Hess",
				pays: "Basel",
				annee: "1846",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS579/2",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7495",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Basel",
		},
		{
			artiste: "Hess Hieronymus",
			titre:
				"Vêtir ceux qui sont nus. Saint Martin partage son manteau avec un mendiant",
			date: "1846",
			dimensions: {
				hauteur: "53",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1919",
			image: "/assets/images/baselmuseum/GKS579-3.jpg",
			provenance: {
				nom: "Hieronymus Hess",
				pays: "Basel",
				annee: "1846",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS579/3",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7496",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Basel",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "L'Île des morts (première version)",
			date: "1880",
			dimensions: {
				hauteur: "111",
				longueur: "155",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1920",
			image: "/assets/images/baselmuseum/GKS588.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Florenz",
				annee: "1880",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS588",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5579",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Schule Konrad Witz",
			titre: "Volet d'autel (à l'intérieur): Nativity",
			date: "1445-1450",
			dimensions: {
				hauteur: "136",
				longueur: "165",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1927",
			image: "/assets/images/baselmuseum/GKS671-1.jpg",
			provenance: {
				nom: "Schule Konrad Witz",
				pays: "St. Gallen",
				annee: "1445/1450",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS671/1",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6669",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Schule Konrad Witz",
			titre:
				"Volet d'autel (face externe): L'incrédulité de saint Thomas et le Christ et la Vierge intercédant auprès de Dieu le Père",
			date: "1445-1450",
			dimensions: {
				hauteur: "136",
				longueur: "165",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1927",
			image: "/assets/images/baselmuseum/GKS671-2.jpg",
			provenance: {
				nom: "Schule Konrad Witz",
				pays: "St. Gallen",
				annee: "1445/1450",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS671/2",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6670",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Witz Konrad",
			titre: "L'ange de l'annonciation",
			date: "1435",
			dimensions: {
				hauteur: "86.5",
				longueur: "69",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1929",
			image: "/assets/images/baselmuseum/GKS713.jpg",
			provenance: {
				nom: "Konrad Witz",
				pays: "Basel",
				annee: "1435",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS713",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6671",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Arnold Böcklin",
			titre: "Les disciples d'Emmaüs",
			date: "1868",
			dimensions: {
				hauteur: "230.5",
				longueur: "301.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1943",
			image: "/assets/images/baselmuseum/GKS911.jpg",
			provenance: {
				nom: "Arnold Böcklin",
				pays: "Basel",
				annee: "1868",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS911",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6691",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Ferdinand Hodler",
			titre: "Portrait de Madame Maria Rosa Krebs-Schüpbach",
			date: "1876",
			dimensions: {
				hauteur: "169.5",
				longueur: "92",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1950",
			image: "/assets/images/baselmuseum/GKS954.jpg",
			provenance: {
				nom: "Ferdinand Hodler",
				pays: "Genf",
				annee: "1876",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS954",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7505",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Urs Graf der Ältere",
			titre: "Lansquenet avec bannière",
			date: "1527",
			dimensions: {
				hauteur: "20.4",
				longueur: "11.3",
				profondeur: "",
			},
			objet: "Gravure",
			anneeacquisition: "1951",
			image: "/assets/images/baselmuseum/GKS960_GKS200-122.jpg",
			provenance: {
				nom: "Urs Graf",
				pays: "Solothurn",
				annee: "1527",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS960",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8903",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Basel",
		},
		{
			artiste: "Ferdinand Hodler",
			titre: "La pension",
			date: "1879",
			dimensions: {
				hauteur: "38",
				longueur: "46",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1952",
			image: "/assets/images/baselmuseum/GKS978.jpg",
			provenance: {
				nom: "Ferdinand Hodler",
				pays: "Genf",
				annee: "1879",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS978",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7507",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Martin P. Bühler, Basel",
		},
		{
			artiste: "Ernst Stückelberg",
			titre: "Portrait de Marie Elisabeth Brüstlein",
			date: "1866",
			dimensions: {
				hauteur: "100.5",
				longueur: "78.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1954",
			image: "/assets/images/baselmuseum/GKS997.jpg",
			provenance: {
				nom: "Ernst Stückelberger",
				pays: "Basel",
				annee: "1866–1903",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS997",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6702",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Marius Etienne François Borgeaud",
			titre: "Mariage breton (Mairie de Rochefort-en-Terre)",
			date: "1913",
			dimensions: {
				hauteur: "60.5",
				longueur: "73",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1956",
			image: "/assets/images/baselmuseum/GKS1007_GKS200-1069.jpg",
			provenance: {
				nom: "Marius Etienne François Borgeaud",
				pays: "Lausanne",
				annee: "1913–1924",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1007",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8941",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Martin P. Bühler",
		},
		{
			artiste: "Otto Friedrich Meyer-Amden",
			titre: "Vaccination",
			date: "1919",
			dimensions: {
				hauteur: "26",
				longueur: "21",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1963",
			image: "/assets/images/baselmuseum/GKS1050_GKS200-1070.jpg",
			provenance: {
				nom: "Otto Friedrich Meyer-Amden",
				pays: "Bern",
				annee: "1919–1921",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1050",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8995",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Pablo Picasso",
			titre: "Sur la plage II",
			date: "1921",
			dimensions: {
				hauteur: "25.6",
				longueur: "31.4",
				profondeur: "",
			},
			objet: "Gravure",
			anneeacquisition: "1972",
			image: "/assets/images/baselmuseum/GKS1093_13_GKS200-1963_Vorderseite.jpg",
			provenance: {
				nom: "Pablo Picasso",
				pays: "Paris",
				annee: "1921",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1093/13",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9130",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Jonas Hänggi",
		},
		{
			artiste: "Alberto Giacometti",
			titre: "Les Pieds dans le plat",
			date: "1933",
			dimensions: {
				hauteur: "13",
				longueur: "9.6",
				profondeur: "",
			},
			objet: "Dessin",
			anneeacquisition: "1975",
			image: "/assets/images/baselmuseum/GKS1111_GKS200-1114_the best.jpg",
			provenance: {
				nom: "Alberto Giacometti",
				pays: "Paris",
				annee: "1933",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1111",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9209",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Martin P. Bühler",
		},
		{
			artiste: "Frank Buchser",
			titre: "Jeune femme en kimono rouge",
			date: "1870 - 1889",
			dimensions: {
				hauteur: "91",
				longueur: "70",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1984",
			image: "/assets/images/baselmuseum/GKS1162_GKS200-1074.jpg",
			provenance: {
				nom: "Frank Buchser",
				pays: "Solothurn",
				annee: "1870/1889",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1162",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9241",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Martin P. Bühler",
		},
		{
			artiste: "Johann Jakob Frey",
			titre: "Montagnes dans la campagne romaine",
			date: "1836-1838",
			dimensions: {
				hauteur: "24",
				longueur: "34",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1986",
			image: "/assets/images/baselmuseum/GKS1170.jpg",
			provenance: {
				nom: "Johann Jakob Frey",
				pays: "Rom",
				annee: "1836/38–1865",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1170",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7521",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Kunstmuseum Basel, Martin P. Bühler",
		},
		{
			artiste: "Johann Jakob Frey",
			titre: "Les temples de Paestum sous la pluie",
			date: "1839-1842",
			dimensions: {
				hauteur: "13",
				longueur: "24",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1986",
			image: "/assets/images/baselmuseum/GKS1171.jpg",
			provenance: {
				nom: "Johann Jakob Frey",
				pays: "Rom",
				annee: "1839/42–1865",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1171",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6734",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Johann Jakob Frey",
			titre: "Ciel orageux sur la campagne romaine",
			date: "1850",
			dimensions: {
				hauteur: "21",
				longueur: "28.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1986",
			image: "/assets/images/baselmuseum/GKS1172.jpg",
			provenance: {
				nom: "Johann Jakob Frey",
				pays: "Rom",
				annee: "1850–1865",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1172",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/6735",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Adrian Zingg",
			titre: "Album Amicorum",
			date: "1757 - 1790",
			dimensions: {
				hauteur: "12.4",
				longueur: "19.5",
				profondeur: "2.7",
			},
			objet: "Dessin",
			anneeacquisition: "2003",
			image: "/assets/images/baselmuseum/GKS1289_GKS200-1081.jpg",
			provenance: {
				nom: "Adrian Zingg",
				pays: "Bern",
				annee: "1757/1790–1816",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "GKS1289",
			emplacement: "Kunstmuseum Basel",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9319",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
	],
	lausannemuseum: [
		{
			artiste: "Charles-Louis-Eugène Burnand",
			titre: "La fuite de Charles le Téméraire",
			date: "1894 - 1895",
			dimensions: {
				hauteur: "320",
				longueur: "540",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1896",
			image: "/assets/images/lausannemuseum/fk460_Vorderseite.jpg",
			provenance: {
				nom: "Charles-Louis-Eugène Burnand",
				pays: "Paris",
				annee: "1894/1895–1896",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK460",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9565",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Hébert Juliette Charlotte",
			titre: "Portrait de Juste Olivier",
			date: "1885",
			dimensions: {
				hauteur: "10",
				longueur: "6.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1896",
			image: "/assets/images/lausannemuseum/fK1129.jpg",
			provenance: {
				nom: "Juliette Charlotte Hébert",
				pays: "Genève",
				annee: "1885–1896",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK1129",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5830",
			licence: "Public Domain Mark 1.0",
			credit: "Federal Art Collection, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Hermanjat, Jacques-Elie-Abraham",
			titre: "Bords du Léman",
			date: "1927",
			dimensions: {
				hauteur: "94",
				longueur: "92",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1927",
			image: "/assets/images/lausannemuseum/fK1147.jpg",
			provenance: {
				nom: "Abraham Hermanjat",
				pays: "Aubonne",
				annee: "1927",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK1147",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7065",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Hügin, Karl Otto",
			titre: "Au café",
			date: "1936",
			dimensions: {
				hauteur: "65.3",
				longueur: "100.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1936",
			image: "/assets/images/lausannemuseum/fK1273.jpg",
			provenance: {
				nom: "Karl Hügin",
				pays: "Zürich",
				annee: "1936",
				pour: "Schweizerische Eidgenossenschaft",
			},
			numeroinventaire: "fK1273",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7682",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Luigi Monteverde",
			titre: "Raisins et pampres",
			date: "1889",
			dimensions: {
				hauteur: "57",
				longueur: "76",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1891",
			image: "/assets/images/lausannemuseum/fK1725_KF100-6378.jpg",
			provenance: {
				nom: "Luigi Monteverde",
				pays: "Lugano",
				annee: "1889–1891",
				pour: "Confederazione Svizzera",
			},
			numeroinventaire: "fK1725",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9578",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Muyden van Jacques Alfred",
			titre: "Les premiers pas (étude)",
			date: "1854",
			dimensions: {
				hauteur: "56.5",
				longueur: "48",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1899",
			image: "/assets/images/lausannemuseum/fK1801.jpg",
			provenance: {
				nom: "Jacques Alfred van Muyden",
				pays: "Genève",
				annee: "1854–1898",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK1801",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/7784",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Ravel Edouard",
			titre: "Fête patronale au Val d'Hérens",
			date: "1889",
			dimensions: {
				hauteur: "211",
				longueur: "166",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1891",
			image: "/assets/images/lausannemuseum/fK2028.jpg",
			provenance: {
				nom: "Edouard Ravel",
				pays: "Genève",
				annee: "1889–1891",
				pour: "Confédération suisse",
			},
			numeroinventaire: "fK2028",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8320",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Rossi Luigi",
			titre: "Route de montagne. Valle di Blenio-Lottigna",
			date: "1872",
			dimensions: {
				hauteur: "31",
				longueur: "43.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1925",
			image: "/assets/images/lausannemuseum/fK2108.jpg",
			provenance: {
				nom: "Luigi Rossi",
				pays: "Milano",
				annee: "1872–1923",
				pour: "Confederazione svizzera",
			},
			numeroinventaire: "fK2108",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8335",
			licence: "Public Domain Mark 1.0",
			credit:
				"Federal Art Collection, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Gleyre Marc-Charles-Gabriel",
			titre: "Jeune fille dans un intérieur pompéien. Sappho",
			date: "1867",
			dimensions: {
				hauteur: "108",
				longueur: "72",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1909",
			image: "/assets/images/lausannemuseum/GKS475.jpg",
			provenance: {
				nom: "Charles Gleyre",
				pays: "Paris",
				annee: "1867",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS475",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5564",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Biéler Ernest",
			titre: "L'eau mystérieuse",
			date: "1911",
			dimensions: {
				hauteur: "144",
				longueur: "376",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1913",
			image: "/assets/images/lausannemuseum/GKS512.jpg",
			provenance: {
				nom: "Ernst Biéler",
				pays: "Savièse",
				annee: "1911–1913",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS512",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5569",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Félix Edouard Vallotton",
			titre: "Nature morte: fruits et légumes",
			date: "1914",
			dimensions: {
				hauteur: "65.5",
				longueur: "81.3",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1927",
			image: "/assets/images/lausannemuseum/GKS666.jpg",
			provenance: {
				nom: "Félix Valloton",
				pays: "Paris",
				annee: "1914",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS666",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5594",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Félix Edouard Vallotton",
			titre: "Portrait des parents de l'artiste",
			date: "1886",
			dimensions: {
				hauteur: "102",
				longueur: "126.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1927",
			image: "/assets/images/lausannemuseum/GKS667.jpg",
			provenance: {
				nom: "Félix Valloton",
				pays: "Vallorbe",
				annee: "1886",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS667",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5595",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Jacques Sablet",
			titre: "Portrait de famille avec la Basilique de Maxence",
			date: "1791",
			dimensions: {
				hauteur: "60",
				longueur: "72",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1932",
			image: "/assets/images/lausannemuseum/GKS742_GKS200-3210_Vorderseite.jpg",
			provenance: {
				nom: "Jacques Sablet",
				pays: "Paris",
				annee: "1791",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS742",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8803",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des beaux-arts Lausanne, Lausanne",
		},
		{
			artiste: "Jacques Sablet",
			titre: "Portrait de famille avec le Colisée",
			date: "1791",
			dimensions: {
				hauteur: "60",
				longueur: "72",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1932",
			image: "/assets/images/lausannemuseum/GKS743_GKS200-3212_Vorderseite.jpg",
			provenance: {
				nom: "Jacques Sablet",
				pays: "Rome",
				annee: "1791",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS743",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8804",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des beaux-arts Lausanne, Lausanne",
		},
		{
			artiste: "Jacques Sablet",
			titre: "La joueuse de harpe",
			date: "1787 - 1789",
			dimensions: {
				hauteur: "63",
				longueur: "75",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1935",
			image: "/assets/images/lausannemuseum/GKS815_GKS200-111.jpg",
			provenance: {
				nom: "Jacques Sablet",
				pays: "Rome",
				annee: "1787/1789",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS815",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8823",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Charles Alexandre Giron",
			titre: "Nature morte",
			date: "1875",
			dimensions: {
				hauteur: "45.5",
				longueur: "37",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1939",
			image: "/assets/images/lausannemuseum/GKS884_Vorderseite.jpg",
			provenance: {
				nom: "Charles Alexandre Giron",
				pays: "Paris",
				annee: "1875",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS884",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8835",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des beaux-arts Lausanne, Lausanne",
		},
		{
			artiste: "Jacques Sablet",
			titre: "Portrait de famille dans un paysage",
			date: "1794",
			dimensions: {
				hauteur: "41",
				longueur: "33.2",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1950",
			image: "/assets/images/lausannemuseum/GKS956_GKS200-1412.jpg",
			provenance: {
				nom: "Jacques Sablet",
				pays: "Paris",
				annee: "1794",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS956",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/8899",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des beaux-arts Lausanne, Lausanne",
		},
		{
			artiste: "Félix Edouard Vallotton",
			titre: "Vue cavalière de La Cagne",
			date: "1921",
			dimensions: {
				hauteur: "81",
				longueur: "60",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1953",
			image: "/assets/images/lausannemuseum/GKS989.jpg",
			provenance: {
				nom: "Félix Vallotton",
				pays: "Cagnes",
				annee: "1921–1925",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS989",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5646",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Wilhelm Gimmi",
			titre: "Nu assis",
			date: "1957",
			dimensions: {
				hauteur: "46.5",
				longueur: "38",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1967",
			image:
				"/assets/images/lausannemuseum/GKS1066_70_GKS200-3208_Vorderseite.jpg",
			provenance: {
				nom: "Wilhelm Gimmi",
				pays: "Chexbres",
				annee: "1957",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1066/70",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9072",
			licence: "All rights reserved",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Jacques Sablet",
			titre: "Le colin-maillard",
			date: "1790",
			dimensions: {
				hauteur: "104",
				longueur: "115.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1979",
			image: "/assets/images/lausannemuseum/GKS1132_GKS200-1410.jpg",
			provenance: {
				nom: "Jacques Sablet",
				pays: "Rome",
				annee: "1790",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1132",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9222",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Félix Edouard Vallotton",
			titre: "La chaste Suzanne",
			date: "1922",
			dimensions: {
				hauteur: "54",
				longueur: "73",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1993",
			image: "/assets/images/lausannemuseum/GKS1240_GKS200-526.jpg",
			provenance: {
				nom: "Félix Vallotton",
				pays: "Paris",
				annee: "1922–1925",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1240",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9267",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Marc-Charles-Gabriel Gleyre",
			titre: "La danse des bacchantes",
			date: "1849",
			dimensions: {
				hauteur: "147",
				longueur: "243",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "1995",
			image: "/assets/images/lausannemuseum/GKS1251_GKS200-2698_Vorderseite.jpg",
			provenance: {
				nom: "Marc-Charles-Gabriel Gleyre",
				pays: "Paris",
				annee: "1849",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1251",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9273",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Musée cantonal des Beaux-Arts, Lausanne",
		},
		{
			artiste: "Félix Edouard Vallotton",
			titre: "Femmes nues aux chats",
			date: "1896-1898",
			dimensions: {
				hauteur: "41",
				longueur: "52",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "2002",
			image: "/assets/images/lausannemuseum/GKS1286.jpg",
			provenance: {
				nom: "Félix Vallotton",
				pays: "Paris",
				annee: "1896",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1286",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/5714",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne",
		},
		{
			artiste: "Jacques Sablet",
			titre:
				"Bord de mer au crépuscule avec paysans napolitains dansant la Tarantella",
			date: "1799",
			dimensions: {
				hauteur: "155",
				longueur: "212",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "2016",
			image: "/assets/images/lausannemuseum/GKS1310_GKS200-370.jpg",
			provenance: {
				nom: "Jacques Sablet",
				pays: "Rome",
				annee: "1803–1844",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1310",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9330",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Nora Rupp, Lausanne",
		},
		{
			artiste: "Jean François Sablet",
			titre: "Vestales versant de l'encens",
			date: "1783",
			dimensions: {
				hauteur: "174.7",
				longueur: "143.5",
				profondeur: "",
			},
			objet: "Peinture",
			anneeacquisition: "2011",
			image: "/assets/images/lausannemuseum/GKS1312_GKS200-328.jpg",
			provenance: {
				nom: "Jean François Sablet",
				pays: "Paris",
				annee: "1783",
				pour: "Confédération suisse",
			},
			numeroinventaire: "GKS1312",
			emplacement: "Musée cantonal des Beaux-Arts, Lausanne",
			lien: "https://kdb.e-pics.ethz.ch/catalog/KdB/r/9332",
			licence: "Public Domain Mark 1.0",
			credit:
				"Gottfried Keller Foundation, Swiss Federal Office of Culture, Berne, Photo: Nora Rupp, Lausanne",
		},
	],
};
